name: Santhosh api trigger

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  CI:
    - name: API Tests run
      shell: bash
      run: |
        curl -L 'https://api.github.com/repos/msanthosh-murugesan/label-test/actions/workflows/github-pages.yml/dispatches' \
        -X POST \
        -H 'Accept: application/vnd.github.v3+json' \
        -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}' \
        -H 'X-GitHub-Api-Version: 2022-11-28' \
        -H 'Content-Type: application/json' \
        -d '{
            "ref": "main"
        }'
    



    
