name: CD

on:
    pull_request:
        branches: [main]
        types: [closed]

jobs:
    CD:
        runs-on: ubuntu-latest
        emvironment:
          name: production
        steps:
          - name: Print CD message
            run: echo "Successful"