name: CD workflow for ruleset

on:
  pull_request:
    types: [opened, synchronize]
  push:

permissions:
  pull-requests: write  

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Extract commit SHA
        id: sha
        run: echo "Commit_SHA=${{ github.event.pull_request.head.sha }}"

      - name: Get commit message
        id: get-commit-message
        run: |
          echo "Pull request commit message:"
          COMMIT_MESSAGE=$(git log --format=%B -n 2 ${{ steps.sha.outputs.Commit_SHA }} | tail -1)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Use the commit message
        run: |
          echo "The commit message is: ${{ env.message }}"
        env:
          message: ${{ steps.get-commit-message.outputs.message }}