name: Condition Testing for synchronize and commit message

on:
  pull_request:
    types: [opened, synchronize]

jobs:
    CD:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: get commit message
          id: commit
          run: |
            echo "commit_msg=$(git log --format=%B -n 2 ${{ github.sha }} | tail -1)" >> "$GITHUB_OUTPUT"

        - name: Test condition
          if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize') && github.event.pull_request.base.ref == 'main' }}
          run: echo "${{ steps.commit.outputs.commit_msg }}"  