name: Condition Testing for synchronize and commit message

on:
  pull_request:
    types: [opened, synchronize]

jobs:
    CD:
      runs-on: ubuntu-latest
      environment:
        name: production
      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: get commit message
          id: commit
          run: |
            echo "commit_msg=(git log --format=%B -n 1 ${{ github.sha }})"
            echo $commit_msg

        - name: Test condition
          if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize') && github.event.pull_request.base.ref == 'main' }}
          run: echo "success"  