name: CD workflow for ruleset

on:
  pull_request:
    types: [opened, synchronize]
  push:

permissions:
  pull-requests: write  

jobs:
    CD:
      runs-on: ubuntu-latest
      environment: staging
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Extract commit SHA
          run: echo "Commit SHA=${{ github.event.pull_request.head.sha }}"

        - name: Get commit message
          id: get-commit-message
          run: |
            echo "Pull request commit message:"
            echo "message=$(git log --format=%B -n 2 ${{ github.event.pull_request.head.sha }})" >> "$GITHUB_OUTPUT"

        - name: Use the commit message
          run: |
            echo "The commit message is: ${{ steps.get-commit-message.outputs.message }}"
          env:
            COMMIT_MESSAGE: ${{ steps.get-commit-message.outputs.message }}

