name: Condition Testing for synchronize and commit message

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
    CD:
      runs-on: ubuntu-latest
      environment: staging
      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Get commit message
          id: get_commit_message
          run: echo "message=$(git log --format=%B -n 2 ${{ github.sha }} | tail -1)" >> "$GITHUB_OUTPUT"

        - name: Extract version type(major or minor or patch)
          id: extract_version_type
          run: |
            COMMIT_MESSAGE="${{ steps.get_commit_message.outputs.message }}"
            
            if [[ $COMMIT_MESSAGE =~ ^(major|Major) ]]; then
              echo "change_type=major" >> "$GITHUB_OUTPUT"
            elif [[ $COMMIT_MESSAGE =~ ^(minor|Minor) ]]; then
              echo "change_type=minor" >> "$GITHUB_OUTPUT"
            elif [[ $COMMIT_MESSAGE =~ ^(patch|Patch) ]]; then
              echo "change_type=patch" >> "$GITHUB_OUTPUT"
            else
              echo "change_type=" >> "$GITHUB_OUTPUT"
            fi