name: CD workflow for ruleset

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
    CD:
      runs-on: ubuntu-latest
      environment: staging
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0

        - name: Get commit message
          id: get_commit_message
          run: echo "message=$(git log --format=%B -n 2 ${{ github.sha }} | tail -1)" >> "$GITHUB_OUTPUT"

        - name: Extract version type(major or minor or patch)
          id: extract_version_type
          run: |
            COMMIT_MESSAGE="${{ steps.get_commit_message.outputs.message }}"
            
            if [[ $COMMIT_MESSAGE =~ ^(major|Major) ]]; then
              echo "change_type=major" >> "$GITHUB_OUTPUT"
            elif [[ $COMMIT_MESSAGE =~ ^(minor|Minor) ]]; then
              echo "change_type=minor" >> "$GITHUB_OUTPUT"
            elif [[ $COMMIT_MESSAGE =~ ^(patch|Patch) ]]; then
              echo "change_type=patch" >> "$GITHUB_OUTPUT"
            else
              echo "change_type=" >> "$GITHUB_OUTPUT"
            fi

        - name: Get PR head commit
          if: github.event_name == 'pull_request'
          id: get_pr_commit
          run: echo "commit_sha=$(jq -r '.pull_request.head.sha' $GITHUB_EVENT_PATH)" >> "$GITHUB_OUTPUT"

        - name: Get commit message for PR
          if: github.event_name == 'pull_request'
          id: get_pr_commit_message
          run: |
            COMMIT_MESSAGE=$(git log --format=%B -n 2 ${{ steps.get_pr_commit.outputs.commit_sha }} | tail -1)
            echo "message=$COMMIT_MESSAGE"   

