name: CD workflow for rulesets

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write  

jobs:
  CD:
    runs-on: ubuntu-latest
    # environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get commit message
        id: get-commit-message
        run: |
          COMMIT_MESSAGE=$(git log --pretty=%B -1 ${{ github.event.pull_request.head.sha }} | tail -1)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"    

      - name: Use the commit message in condition
        if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize') && github.event.pull_request.base.ref == 'main' }}
        run: |
          string="${{ steps.get-commit-message.outputs.message }} "
          if [[ "$string" =~ ^Merge\ branch\ (.*) ]]; then
            echo "The commit message is: ${{ env.message }}"
          else
            echo "Invalid format: doesn't start with 'Merge branch'"
          fi
        env:
          message: ${{ steps.get-commit-message.outputs.message }}    

