name: Dispatch workflow

on:
  workflow_dispatch

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: msanthosh-murugesan/label-test
        token: ${{ secrets.REUSABLE_TOKEN }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: cd app    
    - run: npm i
    - run: npm run test
