name: CI - Push

on:
  push:
    branches:
      - 'cbp-release/**'

jobs:
    context:
        runs-on: ubuntu-latest
        steps:
          - name: Print github context
            env:
              GITHUB_CONTEXT: ${{ toJSON(github) }}
            run: echo "$GITHUB_CONTEXT"