name: Delete stale branches

on:
  workflow_dispatch

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v3.3.0

      - uses: fpicalausa/remove-stale-branches@v1
        with:
          dry-run: true
          days-before-branch-stale: 10